---
title: "Genuine Anovas"
output: pdf_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, cache=FALSE,include=FALSE}
devtools::load_all()
```

```{r data, include=FALSE}
load("../data/dataset.RData") 

summary_participants <- dataset %>%
  group_by( participant, emotion, elicitation, session, group) %>%
  summarize_data() %>%
  mutate(slider = abs(genuine.slider1.mean),
         IES = genuine.rt1.mean/genuine.acc.mean)

pts <- summary_participants %>%
  group_by(group) %>%
  summarise(n = n_distinct(participant)) %>%
  data.frame()

```

## Genuine Experiment Exploratory analysis

Description: Discrimination task using PEDFE video database

State of the data collection:
```{r cars}
pts
```
\tableofcontents

\newpage 
## Anovas

# Genuine Accuracy
```{r GenuineAccuracy, echo=FALSE}
anova_acc_genuine <- aov_ez("participant", "genuine.acc.mean", summary_participants, within = c("emotion","session","elicitation"), between = "group")
posthoc <- emmeans(anova_acc_genuine, pairwise ~ session|emotion, adjust = "bonferroni")

anova_acc_genuine
posthoc
plot(posthoc, comparisons = TRUE)
```

\newpage 
# Genuine Rt
```{r GenuineRt, echo=FALSE}
anova_rt_genuine <- aov_ez("participant", "genuine.rt1.mean", summary_participants, within = c("emotion","session","elicitation"), between = "group")
main_emotion <- emmeans(anova_rt_genuine, pairwise ~ emotion)
main_elicitation <- emmeans(anova_rt_genuine, pairwise ~ elicitation)
posthoc <- emmeans(anova_rt_genuine, pairwise ~ elicitation|emotion, adjust = "bonferroni")
anova_rt_genuine
posthoc
plot(posthoc, comparisons = TRUE)
```

\newpage 
# Genuine slider
```{r Genuineslider, echo=FALSE}
anova_slider_genuine <- aov_ez("participant", "slider", summary_participants, within = c("emotion","session","elicitation"), between = "group")
posthoc <- emmeans(anova_slider_genuine, pairwise ~ elicitation|emotion, adjust = "bonferroni")
anova_slider_genuine
posthoc
plot(posthoc, comparisons = TRUE)
```

\newpage 
# Emotion Accuracy
```{r EmotionAccuracy, echo=FALSE}
anova_acc_emotion <- aov_ez("participant", "emotion.acc.mean", summary_participants, within = c("emotion","session","elicitation"), between = "group")
posthoc <- emmeans(anova_acc_emotion, pairwise ~ emotion|session, adjust = "bonferroni")
anova_acc_emotion
posthoc
plot(posthoc, comparisons = TRUE)
```

\newpage 
# Emotion slider
```{r Emotionslider, echo=FALSE}
anova_slider_emotion <- aov_ez("participant", "emotion.slider1.mean", summary_participants, within = c("emotion","session","elicitation"), between = "group")
posthoc2 <- emmeans(anova_slider_emotion, pairwise ~ session|group|emotion|elicitation, adjust = "bonferroni")
anova_slider_emotion
posthoc2
plot(posthoc2, comparisons = TRUE)
```

