###########################################################################
#
#  Experiment:  GENUINE
#  Programmer:  QUETTIER THOMAS
#  Date:        23/01/2024
# Description: This script aggregates all .csv files generated by PsychoPy
#              and compiles them into a single .RData file for streamlined analysis.
#
#  Update:      16/05/2024
###########################################################################

# Clearing workspace
rm(list=ls()) # Clear the existing workspace to avoid conflicts

# Load dependencies
devtools::load_all() # Load necessary functions and packages
#replace_csv("participant",37) # function to correct error in coding metadata from psychopy

# Data loading
dataset_concatenation("original_data","dataset") # aggregates all .csv files
load("data/dataset.RData") 

# Count participants
n <- length(unique(dataset$participant)) # Calculate the number of unique participants


# Assign participants to groups based on the chronological order of data collection
treatment_group <- c(1,2,3,4,5,11,12,13,14,17,19,22,25,26,27,37)
control_group <- c(6,7,8,9,10,15,16,18,20,21,23,24,28,29,30)
m1_group <- c(31,32,33,34,35,36)

# Retain only experimental trials and create columns for the ccPAS protocol and group assignment
dataset <- dataset %>%
  mutate(ccPAS = ifelse(participant %in% control_group,"STS_IFG", 
                        ifelse(participant %in% m1_group,"M1_IFG", "IFG_STS")),
         group = ifelse(participant %in% control_group,"Control", 
                        ifelse(participant %in% m1_group,"M1","Experimental"))) %>%
  filter(Trials_loop.thisRepN == 0)

# Save the data in .RData format
save(dataset, 
     file = "data/dataset.RData")
